# Development version number
VERSION = 0

# As defined in OPMODE_20200608_v2.2
POWER_TASK_TIMER_DURATION_S = 300

# As defined in OpModePowerTable_Working.
# TODO: Issue this reference.
POWER_OPMODE_OCP_STATE_CONFIG = 4039954176

# Determines the battery voltage at which the low power mode will be activated.
# This value is derived from the ADC to voltage equation in UoS3_SoftwareIcd:
#   v_sense_threshold = v_threshold * R_2 / (R_1 + R_2) = 1.8337408312 V
# where:
#   R_1 = 309 k Ohm
#   R_2 = 100 k Ohm
#   v_threshold = 7.5 V
#
# This value then needs to be converted into raw ADC values, which can be done
# using the equation below:
#   vbatt_vsense_threshold = v_sense_threshold * 1024 / 2.5 V = 751.10024449
#
# The value stored here is of type uint16_t, therefore vbatt_vsense_threshold
# is floor-ed down to 751 to be conservative.
#
# TODO: section reference
POWER_VBATT_VSENSE_LOW_POWER_THRESHOLD = 751

# All rails will reset after an OCP event (all lower 6 bits set to 1)
EPS_RESET_RAIL_AFTER_OCP = 63

# Equates to 12 seconds, meaning that the internal TM4C watchdog and therefore
# the kick for the EPS watchdog shall function at a 6 s period.
EPS_TOBC_TIMER_LENGTH = 4096

# Configuration of which Apps will run in each OpMode
#
# NOTE: See MemStoreManager_public.h for an explanation of the efficiency of
# this storage method.
OPMODE_APPID_TABLE = [
    # Boot Up - none
    [0, 0],

    # Antenna Deploy - Deployment
    [50, 0],

    # Nominal Functioning - Payload, Beacon
    [51, 48],

    # Low Power - none
    [0, 0],

    # Safe - none
    [0, 0],

    # Data Downlink - none
    [0, 0],

    # Config File Update - none
    [0, 0],

    # Picture Taking - Picture
    [49, 0]
]
