# Development version number
VERSION = 0

# As defined in OPMODE_20200608_v2.2
POWER_TASK_TIMER_DURATION_S = 300

# As defined in OpModePowerTable_Working.
# TODO: Issue this reference.
POWER_OPMODE_OCP_STATE_CONFIG = 4039954176

# All rails will reset after an OCP event (all lower 6 bits set to 1)
EPS_RESET_RAIL_AFTER_OCP = 63

# TODO: Demo value of 1 s
EPS_TOBC_TIMER_LENGTH = 4096

# Configuration of which Apps will run in each OpMode
#
# NOTE: See MemStoreManager_public.h for an explanation of the efficiency of
# this storage method.
OPMODE_APPID_TABLE = [
    # Boot Up - none
    [0, 0],

    # Antenna Deploy - Deployment
    [50, 0],

    # Nominal Functioning - Payload, Beacon
    [51, 48],

    # Low Power - none
    [0, 0],

    # Safe - none
    [0, 0],

    # Data Downlink - none
    [0, 0],

    # Config File Update - none
    [0, 0],

    # Picture Taking - Picture
    [49, 0]
]
