# Development version number
version = 0

# As defined in OPMODE_20200608_v2.2
power_task_timer_duration_s = 300

# As defined in OpModePowerTable_Working.
# TODO: Issue this reference.
power_op_mode_ocp_rail_config = 15938319
